"""init structures

Revision ID: 720b08b8f621
Revises: 
Create Date: 2026-04-25 17:36:28.673097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720b08b8f621'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('email', sa.String(length=60), nullable=False),
                    sa.Column('password', sa.String(
                        length=120), nullable=False),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('authors',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(),
                              server_default=sa.text('TRUE'), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('categories',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('books',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('author_id', sa.Integer(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('purchases',
                    sa.Column('book_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('created_by_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('books')
    op.drop_table('categories')
    op.drop_table('authors')
    op.drop_table('users')
    # ### end Alembic commands ###
