services:
  # api:
  #   image: "malazo/fastapi-app-library:${IMAGE_TAG-latest}"
  #   platform: linux/amd64
  #   build:
  #     target: ${TARGET-dev}
  #     context: $PWD/
  #     dockerfile: $PWD/app/Dockerfile
  #     args:
  #         # for build purposes set your UID value here
  #         UID: ${UID-1000}
  #   restart: on-failure
  #   env_file: $PWD/config/.backend_env
  #   user: app
  #   tty: true
  #   entrypoint: ["./entrypoint.sh"]
  #   command: start
  #   ports:
  #       - "8001:8001"
  #       - "8000:8000"
  #   volumes:
  #       - $PWD/app/:/usr/src/backend/app:rwx
  #       - $PWD/bin/entrypoint.sh:/usr/src/backend/entrypoint.sh:rwx
  #       - $PWD/bin/wait-for-it.sh:/usr/src/backend/wait-for-it.sh:rwx
  #       - $PWD/alembic.ini:/usr/src/backend/alembic.ini:rwx
  #       - $PWD/cli.py:/usr/src/backend/cli.py:rwx
  #       - $PWD/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
  #       # - $PWD/docker/wsgi:/etc/wsgi:rw
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #   - fastapi_library
  db:
    image: "mariadb:10.10"
    restart: on-failure
    env_file: $PWD/config/.db_env
    ports:
    - "3306:3306"
    volumes:
    - $PWD/bin/wait-for-it.sh:/tmp/wait-for-it.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "/tmp/wait-for-it.sh -h localhost -p 3306 || exit 1"]
    networks:
    - nestjs_store

    
networks:
  nestjs_store:
    name: nestjs-store
    driver: bridge
    external: false